### ISSUE TITLE
Chat image too big

### ISSUE THREAD

**Issue by DarKDinDoN** [brunocalado/raise-my-hand-plus#1]
Hey, 

Thx for keeping this module alive!

I bit too big, don't you think? xD 
![image](https://user-images.githubusercontent.com/1687854/150125102-a654e2ef-3076-46f0-98ff-6a40444e6b10.png)

Also, if the image option is not check, do we need an image?

**Comment by brunocalado** [comment]
Yes. It's big. You can replace it for something else.

If turn on avatar option this option is useless.

**Comment by brunocalado** [comment]
new setting for size added

**Comment by DarKDinDoN** [comment]
@brunocalado thx for the size option.
I meant that there could be an option with no image as well.

**Comment by brunocalado** [comment]
done

**Comment by brunocalado** [comment]
updated
