### ISSUE TITLE
Suggested features

### ISSUE THREAD

**Issue by RohBawt** [brunocalado/raise-my-hand-plus#12]
I was just thinking I would love a module that did almost exactly this. The only thing more I would ask for is at least two levels of notification. One set let the GM know a player would like attention as soon as convenient and another to let the GM know the player would like to interject as soon as possible, especially useful for GMs who like to help control and smooth the flow of RP.

Would also be cool if there was a way to indicate who requested attention first and in what order after that.

If either of those are reasonable they would make your already awesome tool even more useful for me.

**Comment by brunocalado** [comment]
> I was just thinking I would love a module that did almost exactly this. The only thing more I would ask for is at least two levels of notification. One set let the GM know a player would like attention as soon as convenient and another to let the GM know the player would like to interject as soon as possible, especially useful for GMs who like to help control and smooth the flow of RP.
> 
> Would also be cool if there was a way to indicate who requested attention first and in what order after that.
> 
> If either of those are reasonable they would make your already awesome tool even more useful for me.

It's possible. 

Press the first time: normal behavior
Press the second time: new message
Press the third time: turn off

Something like this?

**Comment by RohBawt** [comment]
That or an option to shift, ctrl, or alt click. Anything that worked for you would be awesome.

**Comment by brunocalado** [comment]
> That or an option to shift, ctrl, or alt click. Anything that worked for you would be awesome.

Do you think the X-Card feature can close this?
