### ISSUE TITLE
X-Card bug

### ISSUE THREAD

**Issue by shecrio** [brunocalado/raise-my-hand-plus#13]
Turning off the X-Card features in the settings does not disable the use of the feature via the keybind, which was fun to find out with conflicting keybinds and that alarm with no volume slider.

**Comment by brunocalado** [comment]
- [ ] Disable X-Card Key
- [ ] Add volume slider for x-card sound 

I'll do it as soon as possible

**Comment by brunocalado** [comment]
fixed
