### ISSUE TITLE
X-Card Macro

### ISSUE THREAD

**Issue by SesuUisu** [brunocalado/raise-my-hand-plus#14]
One of my player's asked if it's possible to have the X-Card also as a macro.
A macro is bigger and helps for easier access in difficult situations. 

Also it was mentioned that the X in the left menu ribbon looks like a "close button".

**Comment by brunocalado** [comment]
You can use the keybind. Press X
![image](https://user-images.githubusercontent.com/4999783/195681188-693e9241-3134-41ac-b3d6-907dcecd466f.png)

You can use this macro:
` window.game.handRaiser.showXCardDialogForEveryoneSocket()`

About the button I don't know. I can change if you find something better at https://fontawesome.com/

**Comment by SesuUisu** [comment]
Thank you for the macro!

For a more obvious symbol maybe one of these:

"fa-solid fa-ban"
"fa-solid fa-circle-xmark"
"fa-regular fa-circle-xmark"
"fa-regular fa-rectangle-xmark"

**Comment by brunocalado** [comment]
> Thank you for the macro!
> 
> For a more obvious symbol maybe one of these:
> 
> "fa-solid fa-ban" "fa-solid fa-circle-xmark" "fa-regular fa-circle-xmark" "fa-regular fa-rectangle-xmark"

I can't access the site at the moment. I'll try to pick one.

**Comment by brunocalado** [comment]
I tested. 
ban don't have the X. The X is important
xmark is igual to what you see
circle/retangle make the x to small
