### ISSUE TITLE
Foundry  VTT v12.xxx compatibility

### ISSUE THREAD

**Issue by Eireman** [brunocalado/raise-my-hand-plus#16]
Any idea as to when we can see this? My weekly game is streamed from 7 different users, and the hand tool is indispensable.

**Comment by brunocalado** [comment]
> Any idea as to when we can see this? My weekly game is streamed from 7 different users, and the hand tool is indispensable.

This module uses https://foundryvtt.com/packages/socketlib I need socketlib to be updated to v12.

**Comment by brunocalado** [comment]
done
