### ISSUE TITLE
GM only sound

### ISSUE THREAD

**Issue by joel-gfdez** [brunocalado/raise-my-hand-plus#17]
First of all, thank you very much for this cool module.

It would be great if there was a setting that could make the sound only audible for the GM. Currently you can make notifications and chat messages discrete so that only the GM can see them, but it's not the same with the sound alerts.

Could we have an option to make sound alerts only audible for the GM?

**Comment by brunocalado** [comment]
I'll try.

**Comment by brunocalado** [comment]
Update the module and test.
