### ISSUE TITLE
Add instructions on how to install previous version (i.e: Foundry v11)

### ISSUE THREAD

**Issue by edoreld** [brunocalado/raise-my-hand-plus#18]
Me and I assume a few others are still running V11. I would like to get this module running but can't manage to find instructions install a version that works for Foundry V11.

**Comment by brunocalado** [comment]
You can download from https://github.com/brunocalado/raise-my-hand-plus/tree/172dc1da4db66871dd12fe168b82cb56cb759668 and manually install.
