### ISSUE TITLE
[FEATURE] Option to display a ui notification to all

### ISSUE THREAD

**Issue by DarKDinDoN** [brunocalado/raise-my-hand-plus#2]
Hello,

A great option that would not overflow the chat and be more visible that the players list would be a ui notification for **everyone or at least the gm**.

Also, in this case, I'm not sure if we really need to have some kind of on/off state to the module. Clicking sends a notification. That's it.
Often my player have to click once, then click again. That's a bit cumbersome.

**Comment by brunocalado** [comment]
There is UI notification. Is not working for you?

Yes. I'm thinking about remove the hand up. But, Is cool to have your hand up on your name.

**Comment by DarKDinDoN** [comment]
@brunocalado You're closing this too fast man.
Yes there is an issue. If my player raise his hand, I, as the GM don't see the notification.

**Comment by brunocalado** [comment]
checking out

**Comment by brunocalado** [comment]
try now

you need socketlib
