### ISSUE TITLE
LANG german

### ISSUE THREAD

**Issue by O-D-C** [brunocalado/raise-my-hand-plus#6]
{
	"raise-my-hand": {
		"UINOTIFICATION": " hat die Hand gehoben.",
		"CHATMESSAGE": "hat die Hand gehoben!",    
    "kandashisfluidcanvas": "Du brauchst das Fluid Canvas Modul!",    
    
		"settings": {
			"displayhand": {
        "name": "Zeige das Handicon in der Spielerliste",
				"hint": "Ein Handicon wird neben dem Namen in der Spielerliste angezeigt."
			},
			"showuinotification": {
        "name": "Zeige UI-Benachrichtigung",
				"hint": "Eine UI-Benachrichtigung (für alle Spieler) wird angezeigt."
			},
			"makeuinotificationpermanent": {
        "name": "Permanente UI-Benachrichtigung",
				"hint": "Die Benachrichtigung wird angezeigt, bis sie aktiv weggeklickt wird."
			},      
			"showuichatmessage": {
				"name": "Zeige eine Chatnachricht",
        "hint": "Eine Benachrichtigung wird im Chat ausgegeben."
			},
			"showimagechatmessage": {
				"name": "Bild zur Chatnachricht",
        "hint": "Zur Chatnachricht wird zusätzlich ein Bild angezeigt."
			},
			"chatimagepath": {
				"name": "Pfad zum Bild",
        "hint": "Gibt den Pfand an, zu dem Bild, das im Chat gezeigt werden soll."
			},
			"chatimagewidth": {
				"name": "Anzeigebreite des Bildes",
        "hint": "Gib in % an, wie gross das Bild angezeigt werden soll."
			},
			"chatmessageimageuserart": {
				"name": "Bild mit Avatarbild ersetzen",
        "hint": "Hierdurch wird das Bild durch das jeweilige Avatarbild ersetzt."
			},
			"playsound": {
				"name": "Sound abspielen",
        "hint": "Ein Audiosignal wird abgespielt."
			},
			"warningsoundpath": {
				"name": "Pfad für das Audiosignal",
        "hint": "Hier kannst du einen Pfad zu einem Audiosignal angeben."
			},
			"warningsoundvolume": {
				"name": "Lautstärke des Audiosignals",
        "hint": "Hier kannst du angeben, wie laut es abgespielt werden soll. 0.1 steht für 10% Lautsärke und 0.6 für 60%."
			},
			"shakescreen": {
				"name": "Bildschirmwackeln",
        "hint": "Der Bildschirmhinhalt wird geschüttelt. BENÖTIGT das Fluid Canvas MODUL!"
			}
		}
  }
}

**Comment by brunocalado** [comment]
Can you find another translated system and share with me from that module this:

    ```js
    {
      "lang": "en",
      "name": "English",
      "path": "lang/en.json"
    },
    {
        "lang": "pt-BR",
        "name": "Português Brasileiro",
        "path": "lang/pt-BR.json"
    },
    {
        "lang": "fr",
        "name": "Français",
        "path": "lang/fr.json"
    }  
    ``` 
    
    I need to now how your language file is defined. The french one is **Français** and the file is usually **fr.json**
            "lang": "fr",
        "name": "Français",
        "path": "lang/fr.json"
    
    tks

**Comment by brunocalado** [comment]
I think It's working now.
