### ISSUE TITLE
Discrete Raising Hand

### ISSUE THREAD

**Issue by mouse0270** [brunocalado/raise-my-hand-plus#7]
So I wanted to check in to see if this was something that was in the scope of this project or not. As this module sounds like what I wanted but doesn't quite do as I expected.

Right now, I am running a table of 7 players and were all friends, but we tend to talk over each other and get off topic quite a lot. So I was look for a module that would notify me when a player wanted my attention. However I wanted something really discrete. This seems like it. However this module is FAR from discrete and it makes my shy players basically refuse to use it.

So my question is, are these following requests in the scope of this project or should I be trying to find another project that suits my needs more: 
- Add an option to make raising your hand discrete, Only the GM sees the notifications in the player list, ui, or chat.
- Add a Window that will queue people who raised there hands, so I can see who raised their hands and in which order they raised them, hitting the button again will not move the user in the GUI they will stay there until I have removed them.

**Comment by brunocalado** [comment]
**Add an option to make raising your hand discrete, Only the GM sees the notifications in the player list, ui, or chat.**
Did you check settings? You can make it really discrete. Check out and you find something.
But, make the notification show to just the GM is something that I can try do.

**Add a Window that will queue people who raised there hands, so I can see who raised their hands and in which order they raised them, hitting the button again will not move the user in the GUI they will stay there until I have removed them.**
This is beyond my skills. But, I can check it out.

**Comment by mouse0270** [comment]
When I said discrete, I don't mean to the UI, I mean to the players. For example, right now it is shown to everyone, which isn't very discrete, every player knows who triggered the raise hand. If you had this it will be amazing, thank you.

As for the other thing, when I have some time, I could take a look. I am OCD about UI/UX design. Maybe make a pull request.

**Comment by brunocalado** [comment]
**When I said discrete, I don't mean to the UI, I mean to the players. For example, right now it is shown to everyone, which isn't very discrete, every player knows who triggered the raise hand. If you had this it will be amazing, thank you.**
Ok. I'm adding a GM only notification.

**As for the other thing, when I have some time, I could take a look. I am OCD about UI/UX design. Maybe make a pull request.**
Cool!

**Comment by brunocalado** [comment]
gm only notification ok

can't do the queue thing, you can PR, or just look into the chat message order.
